/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`
declare namespace Cloudflare {
	interface Env {
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
